---
- name: Stop traefik container
  hosts: machines
  gather_facts: yes
  vars:
    service_name: traefik
  tasks:
    - name: "Stop container"
      containers.podman.podman_container:
        name: "{{ service_name }}"
        state: stopped
    - name: "Stop podman systemd socket"
      ansible.builtin.shell: systemctl --user stop podman.socket
