---
- name: Stop coredns container
  hosts: machines
  gather_facts: yes
  vars:
    service_name: coredns
  tasks:
    - name: "Stop container"
      containers.podman.podman_container:
        name: "{{ service_name }}"
        state: stopped
