---
- name: Build bind9 image # doing this locally right now since I don't have a CI thing going
  hosts: localhost
  gather_facts: yes
  vars:
    build_path: ../bind9
    image_name: bind9-dns-server
    image_tag: 0.0.1
    image_archive: bind9-dns-server.tar
  tasks:
    - name: "Build image using podman"
      containers.podman.podman_image:
        name: {{ image_name }}
        path: {{ build_path }}
        tag: {{ image_tag }}
        build:
          format: docker
    - name: "Export image to tar file"
      ansible.builtin.tempfile:
        state: directory
        suffix: {{ image_name }}
      register: tempdirectory
      containers.podman.podman_save:
        image: {{ image_name }}
        tag: {{ image_tag }}
        dest: {{ tempdirectory.path}}/{{ image_archive }}
      when: tempdirectory.path is defined

- name: Deploy bind9 image
  hosts: machines
  gather_facts: yes
  vars:
    port: 53
    image_archive: bind9-dns-server.tar
    
